### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by arearntsen** [thambitheevan/AreG#1]
Hi Rajatheevan!
I have checked out your code. Looks very good. Looks to me like some of it works good. For the nlocArray, it looks like it just offsets the polygon the desired distance. Was this intentional? What I was looking for was a perimeter around.

How it is now:
![image](https://user-images.githubusercontent.com/19689650/95588589-e66e3180-0a43-11eb-81ef-7cb41e395824.png)

How I want it to be:
![image](https://user-images.githubusercontent.com/19689650/95588721-0b62a480-0a44-11eb-8e90-cadf4484bd57.png)

**Comment by arearntsen** [comment]
And by tha way. No hurry fixing this until I payed you 😜

**Comment by thambitheevan** [comment]
Resolved in the latest commit
